### ISSUE TITLE
前端问题

### ISSUE THREAD

**Issue by songoow** [Terry-Ye/im#2]
非常感谢前面的解答，我在本地运行基本没有问题，但前端还有一些问题，实在不好意思，我把https://www.texixi.com 替换localhost , 发现前端界面还是有问题，能麻烦把demo里面对三个html文件修改下，让我参照对比下吗，谢谢

**Comment by songoow** [comment]
问题描述： 我在本地登陆http://localhost:1999/ 点击注册，登陆相关按钮，最终都是重定向https://www.texixi.com：1999

**Comment by Terry-Ye** [comment]
看一下这个目录的html 文件 ， 
`cd $GOPATH/src/im/demo`
把https://www.texixi.com:1999 改成http://localhost:1999/ 应该就可以了。批量替换一下

**Comment by songoow** [comment]
一共有三个端口
https://www.texixi.com:1999/
https://www.texixi.com:8080/
https://www.texixi.com:6921/
我替换成了  http://localhost:端口/，只能实现注册功能，不能实现登陆
感觉这个关系，wss://www.texixi.com:8911/ws ,我替换成wss://localhost:8911/ws   也没有解决问题，请问该如何修改

**Comment by Terry-Ye** [comment]
你是使用http协议的
你把
`wss://localhost:8911/ws`
改成
`ws://localhost:8911/ws`

不能实现登录是报什么错误？

**Comment by songoow** [comment]
注册和登陆都实现了，其他功能还没有实现，没有显示在线人数，也不能聊天，我去尝试调用IM-api的时候，注册接口和登陆接口都能正常返回数据，但是检查更新在线人数（由ws推送）接口的时候，返回的是NO response，
发送聊天信息的时候  打开开发者工具里面 
 pushRoom?auth=5c894da0858207aa&rid=1    显示为红色  ，localhost:1999 会弹出异常

**Comment by Terry-Ye** [comment]
你查看comet 和logic 对应 log 文件看看报什么错误
或者你测试阶段使用以下的调试方法，先把im系统起的进程kill掉
例：
`cd $GOPATH/src/im/comet/`
`go run *.go  # 你需要在comet、logic、job 层都这样起服务，实时看log，方便调试`

**Comment by songoow** [comment]
好的，谢谢，我再仔细看一下
